Catkin-ProjectName: darc_benchmark
Description:
Author: Morten Kjaergaard <mkjargaard@willowgarage.com>
Maintainer: Morten Kjaergaard <mkjargaard@willowgarage.com>
Homepage:
Vcs-Git:

Version: 0.0.1

Depends: darc

Catkin-CopyrightType:
Catkin-DebRulesType: python_distutils
